In [1]:
import pandas as pd

In [7]:
filepath = "C:/Users/Pawan Kataria/Downloads/CPI2022_GlobalResultsTrends.xlsx"
df = pd.read_excel(filepath)
print(df)

    Corruption Perceptions Index 2022: Global scores Unnamed: 1 Unnamed: 2  \
0                                                NaN        NaN        NaN
1                                Country / Territory       ISO3     Region
2                                        Afghanistan        AFG         AP
3                                            Albania        ALB        ECA
4                                            Algeria        DZA       MENA
..                                               ...        ...        ...
177                                        Venezuela        VEN        AME
178                                          Vietnam        VNM         AP
179                                            Yemen        YEM       MENA
180                                           Zambia        ZMB        SSA
181                                         Zimbabwe        ZWE        SSA

         Unnamed: 3 Unnamed: 4      Unnamed: 5         Unnamed: 6 Unnamed: 7  \
0               NaN        NaN             NaN                NaN        NaN
1    CPI score 2022       Rank  Standard error  Number of sources   Lower CI
2                24        150        6.299999                  4     13.668
3                36        101        1.316355                  8   33.84118
4                33        116        1.673809                  6   30.25495
..              ...        ...             ...                ...        ...
177              14        177        1.296945                  8   11.87301
178              42         77        1.497007                  8   39.54491
179              16        176        1.975074                  7   12.76088
180              33        116        1.495884                  9   30.54675
181              23        157         1.53208                  8   20.48739

    Unnamed: 8                     Unnamed: 9  ...  \
0          NaN                            NaN  ...
1     Upper CI  African Development Bank CPIA  ...
2       34.332                            NaN  ...
3     38.15882                            NaN  ...
4     35.74504                            NaN  ...
..         ...                            ...  ...
177   16.12699                            NaN  ...
178   44.45509                            NaN  ...
179   19.23912                            NaN  ...
180   35.45325                             34  ...
181   25.51261                             19  ...

                                     Unnamed: 12  \
0                                            NaN
1    Economist Intelligence Unit Country Ratings
2                                            NaN
3                                             37
4                                             37
..                                           ...
177                                           20
178                                           37
179                                           20
180                                           37
181                                           37

                          Unnamed: 13                           Unnamed: 14  \
0                                 NaN                                   NaN
1    Freedom House Nations in Transit  Global Insights Country Risk Ratings
2                                 NaN                                    10
3                                  42                                    35
4                                 NaN                                    35
..                                ...                                   ...
177                               NaN                                    10
178                               NaN                                    47
179                               NaN                                    10
180                               NaN                                    35
181                               NaN                                    22

                            Unnamed: 15           Unnamed: 16  \
0                                   NaN                   NaN
1    IMD World Competitiveness Yearbook  PERC Asia Risk Guide
2                                   NaN                   NaN
3                                   NaN                   NaN
4                                   NaN                   NaN
..                                  ...                   ...
177                                  24                   NaN
178                                 NaN                    39
179                                 NaN                   NaN
180                                 NaN                   NaN
181                                 NaN                   NaN

                              Unnamed: 17                     Unnamed: 18  \
0                                     NaN                             NaN
1    PRS International Country Risk Guide  Varieties of Democracy Project
2                                     NaN                              43
3                                      32                              27
4                                      24                              29
..                                    ...                             ...
177                                    15                               9
178                                    41                              44
179                                    15                              11
180                                    32                              49
181                                    15                              20

         Unnamed: 19               Unnamed: 20  \
0                NaN                       NaN
1    World Bank CPIA  World Economic Forum EOS
2                NaN                       NaN
3                NaN                        42
4                NaN                       NaN
..               ...                       ...
177              NaN                        13
178              NaN                        55
179               10                        30
180               27                        30
181               27                       NaN

                                 Unnamed: 21
0                                        NaN
1    World Justice Project Rule of Law Index
2                                         16
3                                         29
4                                         36
..                                       ...
177                                        9
178                                       36
179                                      NaN
180                                       36
181                                       23

[182 rows x 22 columns]

In [8]:
df = pd.read_excel(filepath, header=2)
df

,Country / Territory,ISO3,Region,CPI score 2022,Rank,Standard error,Number of sources,Lower CI,Upper CI,African Development Bank CPIA,...,Economist Intelligence Unit Country Ratings,Freedom House Nations in Transit,Global Insights Country Risk Ratings,IMD World Competitiveness Yearbook,PERC Asia Risk Guide,PRS International Country Risk Guide,Varieties of Democracy Project,World Bank CPIA,World Economic Forum EOS,World Justice Project Rule of Law Index
0,Afghanistan,AFG,AP,24,150,6.299999,4,13.66800,34.33200,NaN,...,NaN,NaN,10,NaN,NaN,NaN,43.0,NaN,NaN,16.0
1,Albania,ALB,ECA,36,101,1.316355,8,33.84118,38.15882,NaN,...,37.0,42.0,35,NaN,NaN,32.0,27.0,NaN,42.0,29.0
2,Algeria,DZA,MENA,33,116,1.673809,6,30.25495,35.74504,NaN,...,37.0,NaN,35,NaN,NaN,24.0,29.0,NaN,NaN,36.0
3,Angola,AGO,SSA,33,116,2.807703,7,28.39537,37.60463,NaN,...,20.0,NaN,47,NaN,NaN,32.0,46.0,NaN,22.0,28.0
4,Argentina,ARG,AME,38,94,2.334808,7,34.17091,41.82909,NaN,...,37.0,NaN,35,24.0,NaN,32.0,47.0,NaN,NaN,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Venezuela,VEN,AME,14,177,1.296945,8,11.87301,16.12699,NaN,...,20.0,NaN,10,24.0,NaN,15.0,9.0,NaN,13.0,9.0
176,Vietnam,VNM,AP,42,77,1.497007,8,39.54491,44.45509,NaN,...,37.0,NaN,47,NaN,39.0,41.0,44.0,NaN,55.0,36.0
177,Yemen,YEM,MENA,16,176,1.975074,7,12.76088,19.23912,NaN,...,20.0,NaN,10,NaN,NaN,15.0,11.0,10.0,30.0,NaN
178,Zambia,ZMB,SSA,33,116,1.495884,9,30.54675,35.45325,34.0,...,37.0,NaN,35,NaN,NaN,32.0,49.0,27.0,30.0,36.0
179,Zimbabwe,ZWE,SSA,23,157,1.532080,8,20.48739,25.51261,19.0,...,37.0,NaN,22,NaN,NaN,15.0,20.0,27.0,NaN,23.0

In [9]:
df.head()

,Country / Territory,ISO3,Region,CPI score 2022,Rank,Standard error,Number of sources,Lower CI,Upper CI,African Development Bank CPIA,...,Economist Intelligence Unit Country Ratings,Freedom House Nations in Transit,Global Insights Country Risk Ratings,IMD World Competitiveness Yearbook,PERC Asia Risk Guide,PRS International Country Risk Guide,Varieties of Democracy Project,World Bank CPIA,World Economic Forum EOS,World Justice Project Rule of Law Index
0,Afghanistan,AFG,AP,24,150,6.299999,4,13.66800,34.33200,NaN,...,NaN,NaN,10,NaN,NaN,NaN,43.0,NaN,NaN,16.0
1,Albania,ALB,ECA,36,101,1.316355,8,33.84118,38.15882,NaN,...,37.0,42.0,35,NaN,NaN,32.0,27.0,NaN,42.0,29.0
2,Algeria,DZA,MENA,33,116,1.673809,6,30.25495,35.74504,NaN,...,37.0,NaN,35,NaN,NaN,24.0,29.0,NaN,NaN,36.0
3,Angola,AGO,SSA,33,116,2.807703,7,28.39537,37.60463,NaN,...,20.0,NaN,47,NaN,NaN,32.0,46.0,NaN,22.0,28.0
4,Argentina,ARG,AME,38,94,2.334808,7,34.17091,41.82909,NaN,...,37.0,NaN,35,24.0,NaN,32.0,47.0,NaN,NaN,44.0

What five countries were least corrupt in 2022?

In [10]:
df["CPI score 2022"]

0      24
1      36
2      33
3      33
4      38
       ..
175    14
176    42
177    16
178    33
179    23
Name: CPI score 2022, Length: 180, dtype: int64

In [11]:
df["CPI score 2022"].sort_values(ascending=False)

42     90
55     87
116    87
121    84
154    83
       ..
177    16
175    14
156    13
149    13
147    12
Name: CPI score 2022, Length: 180, dtype: int64

In [13]:
df.set_index("Country / Territory")["CPI score 2022"].sort_values(ascending=False).head()

Country / Territory
Denmark        90
Finland        87
New Zealand    87
Norway         84
Sweden         83
Name: CPI score 2022, dtype: int64

What five countries were most corrupt in 2022?

In [14]:
df.set_index('Country / Territory')["CPI score 2022"].sort_values(ascending=True).head()

Country / Territory
Somalia        12
Syria          13
South Sudan    13
Venezuela      14
Yemen          16
Name: CPI score 2022, dtype: int64

Which region of the world was least corrupt?

In [15]:
df.groupby('Region')["CPI score 2022"].mean()

Region
AME      42.968750
AP       45.129032
ECA      35.210526
MENA     37.500000
SSA      32.387755
WE/EU    65.516129
Name: CPI score 2022, dtype: float64

In [16]:
df.groupby('Region')["CPI score 2022"].median()

Region
AME      39.5
AP       40.0
ECA      36.0
MENA     39.0
SSA      30.0
WE/EU    62.0
Name: CPI score 2022, dtype: float64

In [18]:
df.groupby('Region')["CPI score 2022"].mean().sort_values()

Region
SSA      32.387755
ECA      35.210526
MENA     37.500000
AME      42.968750
AP       45.129032
WE/EU    65.516129
Name: CPI score 2022, dtype: float64

In [19]:
df.groupby('Region')["CPI score 2022"].mean().idxmax()

'WE/EU'

Which five countries have made the greatest improvement in 10 years, between the 2012 report and the 2022 report?

In [20]:
df = pd.read_excel(filepath, sheet_name=2, header=2)
df

,Country,ISO3,Region,CPI 2022,CPI 2012,Unnamed: 5,Country.1,ISO3.1,Region.1,CPI 2022.1,...,ISO3.8,Region.8,CPI 2022.8,CPI 2020,Unnamed: 53,Country.9,ISO3.9,Region.9,CPI 2022.9,CPI 2021
0,Angola,AGO,SSA,33,22,NaN,Angola,AGO,SSA,33.0,...,AUT,WE/EU,71.0,76.0,NaN,Ireland,IRL,WE/EU,77.0,74.0
1,Armenia,ARM,ECA,46,34,NaN,Armenia,ARM,ECA,46.0,...,NaN,NaN,NaN,NaN,NaN,Luxembourg,LUX,WE/EU,77.0,81.0
2,Australia,AUS,AP,75,85,NaN,Australia,AUS,AP,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bosnia and Herzegovina,BIH,ECA,34,42,NaN,Bosnia and Herzegovina,BIH,ECA,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,CAN,AME,74,84,NaN,Cote d'Ivoire,CIV,SSA,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Cote d'Ivoire,CIV,SSA,37,29,NaN,Cyprus,CYP,WE/EU,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Cyprus,CYP,WE/EU,52,66,NaN,Czech Republic,CZE,WE/EU,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Czech Republic,CZE,WE/EU,56,49,NaN,Estonia,EST,WE/EU,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Estonia,EST,WE/EU,74,64,NaN,Greece,GRC,WE/EU,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ethiopia,ETH,SSA,38,33,NaN,Guyana,GUY,AME,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Greece,GRC,WE/EU,52,36,NaN,Hungary,HUN,WE/EU,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Guatemala,GTM,AME,24,33,NaN,Italy,ITA,WE/EU,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Guyana,GUY,AME,40,28,NaN,"Korea, South",KOR,AP,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Honduras,HND,AME,23,28,NaN,Lesotho,LSO,SSA,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Hungary,HUN,WE/EU,42,55,NaN,Liberia,LBR,SSA,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Ireland,IRL,WE/EU,77,69,NaN,Mongolia,MNG,AP,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Italy,ITA,WE/EU,56,42,NaN,Nicaragua,NIC,AME,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Korea, South",KOR,AP,63,56,NaN,Saint Lucia,LCA,AME,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Laos,LAO,AP,31,21,NaN,Turkey,TUR,ECA,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Latvia,LVA,WE/EU,59,49,NaN,Ukraine,UKR,ECA,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Lebanon,LBN,MENA,24,30,NaN,Uzbekistan,UZB,ECA,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Liberia,LBR,SSA,26,41,NaN,Venezuela,VEN,AME,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Nepal,NPL,AP,34,27,NaN,Vietnam,VNM,AP,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Nicaragua,NIC,AME,19,29,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Saint Lucia,LCA,AME,55,71,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Senegal,SEN,SSA,43,36,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Seychelles,SYC,SSA,70,52,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Sri Lanka,LKA,AP,36,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Syria,SYR,MENA,13,26,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Turkey,TUR,ECA,36,49,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Ukraine,UKR,ECA,33,26,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Uzbekistan,UZB,ECA,31,17,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Vietnam,VNM,AP,42,31,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Yemen,YEM,MENA,16,23,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df = pd.read_excel(filepath, sheet_name=2, header=2, usecols=[0,1,2,3,4])
df.head(3)

     Country ISO3 Region  CPI 2022  CPI 2012
0     Angola  AGO    SSA        33        22
1    Armenia  ARM    ECA        46        34
2  Australia  AUS     AP        75        85

In [25]:
df['change'] = df['CPI 2022'] - df['CPI 2012']
df['change'].sort_values(ascending=False).head()

26    18
10    16
16    14
31    14
12    12
Name: change, dtype: int64

In [26]:
df.set_index('Country')['change'].sort_values(ascending=False).head()

Country
Seychelles    18
Greece        16
Italy         14
Uzbekistan    14
Guyana        12
Name: change, dtype: int64